services:
  elasticsearch:
    image: elasticsearch:7.17.23
    container_name: elasticsearch
    hostname: elasticsearch
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 4G
    restart: always
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=true 
      - cluster.name=docker-cluster
      - ELASTIC_PASSWORD=nY5AQz37ZZIfMev9nY5AQz37ZZIfMev9
      - TZ=America/Sao_Paulo
    healthcheck:
      test: curl -u elastic:nY5AQz37ZZIfMev9nY5AQz37ZZIfMev9 -f http://elasticsearch:9200/_cluster/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
        - rede-elastic-kibana
  kibana:
    depends_on:
       - elasticsearch
    image: kibana:7.17.23
    container_name: kibana
    hostname: kibana
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 2G
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=nY5AQz37ZZIfMev9nY5AQz37ZZIfMev9
      - TZ=America/Sao_Paulo
    healthcheck:
      test: curl -f http://kibana:5601/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5601:5601"
    networks:
        - rede-elastic-kibana

volumes:
  elastic_data:

networks:
  rede-elastic-kibana:
    driver: bridge
